[phases.build]
cmds = [
    "mkdir -p storage/framework/{sessions,views,cache}",
    "mkdir -p storage/app/public/livewire-tmp",
    "mkdir -p storage/app/private/livewire-tmp",
    "mkdir -p storage/app/livewire-tmp",
    "mkdir -p bootstrap/cache",
    "chmod -R 777 storage bootstrap/cache",
    "npm run build",
    "chmod +x scripts/railway-start.sh"
]

[start]
cmd = "sh scripts/railway-start.sh"
